name: Execute Script

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v5

        - name: List Repo files
          run: ls -ltra
        
        - name: Executing shell script
          run: |
            chmod +x ascii-script.sh            
            ./ascii-script.sh

        