name: My first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v5
        
        - name: Welcome Message THEN list THEN show file content
          run: |
              echo "My first Github Actions job"
              ls
              cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "This is a cow talking" >> dragon.txt

        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md